
export default {

 FETCHING_COLLEGES: 'FETCHING_COLLEGES',
 SELECT_COLLEGE: 'SELECT_COLLEGE',
 SELECT_DEPARTMENT: 'SELECT_DEPARTMENT',
 SELECT_SEMESTER: 'SELECT_SEMESTER',

 FETCH_NOTICES: 'FETCH_NOTICES',
 RELOAD_NOTICES: 'RELOAD_NOTICES',

 ROUTE_CHANGED: 'ROUTE_CHANGED'



}
